apiVersion: v1
kind: Secret
metadata:
  name: report-api-secret
type: Opaque
stringData:
  SECRET_KEY: "your-secret-key-change-this"
  DEBUG: "False"
  DB_NAME: "reportdb"
  DB_USER: "reportuser"
  DB_PASSWORD: "reportpass"
  DB_HOST: "postgres-service"
  DB_PORT: "5433"
